name: allinone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  intl: ^0.17.0
  provider: ^6.0.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.1.8

flutter_icons:
  image_path: "assets/icon/icon.jpg"
  android: true
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  ios: true
  macos: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/cool_smiley.png
    - assets/images/brush.png

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 700
